### PR TITLE
add lastfm service

### PR DESCRIPTION
**Pull request by matthewdias**
Creating the pr to track. Not ready to merge.

### CODE REVIEW

**Comment by matthewdias** [comment]
I'm having trouble getting the SearchForm to work. Seems like the state is always `submitting: false`. Any help @kudos ?

**Comment by kudos** [comment]
@matthewdias I'll try to get a look at this tonight, it's been a hectic week :)

**Comment by matthewdias** [comment]
@kudos have you had a chance to check this out yet? No worries if you're busy. Also to be clear, I haven't made any changes yet, just trying to get it to work locally.

**Comment by matthewdias** [comment]
@kudos any particular reason you closed this? honestly forgot about it, but id still like to build this out if you dont have any problems with having last.fm support.

**Comment by kudos** [comment]
@matthewdias opening a PR early is a good idea, but since it's been a year and there's nothing to give feedback on I figured it was abandoned. Let's open another PR when there's something more substantial?

**Comment by matthewdias** [comment]
sounds good 👍

**Pull request closed without merging**
